### ISSUE TITLE
On Mac OS X 10.12.6, nimble install spry produces binaries that fail on execution

### ISSUE THREAD

**Issue by truedat101** [gokr/spry#10]
After installing nim using brew, nimble install spry produces a spry and ispry binary that will fail with:

could not load: libsnappy.dylib
compile with -d:nimDebugDlOpen for more information

**Comment by truedat101** [comment]
May be related to #2 , it appears snappy is an external dependency .  I am checking into whether building with nimble directly (not following the README instructions, in other words) will be preferred approach.

**Comment by truedat101** [comment]
Unfortunately, while the .nimble file produces a comprehensive build, snappy is a library that may/may not exist on a platform.  In the README, section for dependencies should include lib snappy.  On Mac OS X, this is "brew install snappy".

**Comment by truedat101** [comment]
So as mentioned, above, I can fix the error by installing snappy library (native).  Nimble in this case only handles the wrapper around snappy via nimsnappy.

**Comment by gokr** [comment]
Yeah, thanks. I will update the README around these things.

**Comment by truedat101** [comment]
On debian, I think this would be "sudo apt-get install libsnappy-dev"

**Comment by kamidev** [comment]
Yes, I also had to install Snappy on MacOS. "brew install snappy" works just fine.

**Comment by gokr** [comment]
I am going through this now - fixing the README etc. I just had a lot of updates to do on my mac first. And I am fiddling with Windows - unfortunately choosenim is a tad b0rken there.

**Comment by gokr** [comment]
I have updated the README, this is all of course a bit messy, especially on Windows.

**Comment by truedat101** [comment]
@gokr I can try it out on windows when you are ready.  Much easier to test in a clean environment.

**Comment by gokr** [comment]
Yeah, I have updated instructions, eo test. But now I am also restructuring spry into two separate nimble packages - spry(interpreter) and spryvm (library).

**Comment by gokr** [comment]
Also, I am on gitter btw, gokr/spry
