### ISSUE TITLE
Add Docker image to README

### ISSUE THREAD

**Issue by thalesmg** [gokr/spry#12]
Docker images are a great way to try things out.

I have made one image so I could try out the language, if you would like to use it.

```bash
$ docker run --rm -it thalesmg/spry

Welcome to interactive Spry!
An empty line will evaluate previous lines, so hit enter twice.
>>> echo "Hello World!"
>>>
Hello World!
nil
>>>
```

Github: https://github.com/thalesmg/docker-spry
Docker Hub: https://hub.docker.com/r/thalesmg/spry/

**Comment by gokr** [comment]
Really nice! I will include it on the website which is btw up again on http://sprylang.se
