### ISSUE TITLE
nimble install has errors on Mac OS 10.13.6

### ISSUE THREAD

**Issue by jpfersich** [gokr/spry#13]
This what I get when i run nimble install:

Johns-iMac:spry jpfersich$ nimble install
  Verifying dependencies for spry@0.7.1
      Info: Dependency on spryvm@any version already satisfied
  Verifying dependencies for spryvm@0.7.1
      Info: Dependency on python@any version already satisfied
  Verifying dependencies for python@1.2
      Info: Dependency on ui@any version already satisfied
  Verifying dependencies for ui@0.9.2
      Info: Dependency on nimsnappy@any version already satisfied
   Warning: Package 'nimsnappy' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'nimsnappy.nim', but a file named 'snappy.nim' was found. This will be an error in the future.
      Hint: If this is the primary source file in the package, rename it to 'nimsnappy.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'nimsnappy', then move it into a 'nimsnappy/' subdirectory. If it's a test file or otherwise not required to build the the package 'nimsnappy.nim', prevent its installation by adding `skipFiles = @["snappy.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
  Verifying dependencies for nimsnappy@0.1.1
 Installing spry@0.7.1
   Building spry/spry using c backend
       Tip: 16 messages have been suppressed, use --verbose to show them.
     Error: nimble.nim(1106)         nimble
        ... nimble.nim(1044)         doAction
        ... nimble.nim(474)          install
        ... nimble.nim(359)          installFromDir
        ... nimble.nim(253)          buildFromDir
        ... nimble.nim(245)          buildFromDir
        ... Build failed for package: spry
        ... Details:
        ... nimble.nim(1106)         nimble
        ... nimble.nim(1044)         doAction
        ... nimble.nim(474)          install
        ... nimble.nim(359)          installFromDir
        ... nimble.nim(253)          buildFromDir
        ... nimble.nim(237)          buildFromDir
        ... tools.nim(37)            doCmd
        ... Execution failed with exit code 1
        ... Command: "/Users/jpfersich/.nimble/bin/nim" c --noBabelPath -d:release --path:"/Users/jpfersich/.nimble/pkgs/spryvm-0.7.1"  --path:"/Users/jpfersich/.nimble/pkgs/python-1.2"  --path:"/Users/jpfersich/.nimble/pkgs/ui-0.9.2"  --path:"/Users/jpfersich/.nimble/pkgs/nimsnappy-0.1.1"  -o:"/Users/jpfersich/Documents/GitHub/spry/bin/spry" "/Users/jpfersich/Documents/GitHub/spry/src/spry.nim"
        ... Output: Hint: used config file '/Users/jpfersich/.choosenim/toolchains/nim-0.19.0/config/nim.cfg' [Conf]
        ... Hint: used config file '/Users/jpfersich/Documents/GitHub/spry/src/nim.cfg' [Conf]
        ... Hint: used config file '/Users/jpfersich/Documents/GitHub/spry/src/spry.nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: spry [Processing]
        ... Hint: os [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: strformat [Processing]
        ... Hint: macros [Processing]
        ... Hint: posix [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: parseopt2 [Processing]
        ... spry.nim(9, 12) Warning: Use the 'parseopt' module instead; parseopt2 is deprecated [Deprecated]
        ... Hint: spryvm [Processing]
        ... Hint: sequtils [Processing]
        ... Hint: tables [Processing]
        ... Hint: hashes [Processing]
        ... ../../../../.nimble/pkgs/spryvm-0.7.1/spryvm/spryvm.nim(572, 12) Error: type mismatch: got <nil> but expected 'string'

Looks like problem in spryvm?

**Comment by gokr** [comment]
Hey!

Hmmm, I will take a look, Spry has been a bit on hold from me - been too busy with another "burn my spare time" project: (https://getcanoe.io).

But it would be fun to give it some more love! Especially if people actually want to play with it ;)

**Comment by jpfersich** [comment]
Well, its getting some discussion over in the Pharo Users mailing list, so there might be some interest sparked from there. I recognize you from the old days on Squeak.

**Comment by jpfersich** [comment]
And I got the same error on Ubuntu 16.04.

**Comment by jpfersich** [comment]
Here the output from Ubuntu 16.04:

jpfersich@ubuntu64-001:~/git-stuff/spry$ nimble install
  Verifying dependencies for spry@0.7.1
    Prompt: No local packages.json found, download it from internet? [y/N]
    Answer: y
Downloading Official package list
    Success Package list downloaded.
 Installing spryvm@any version
Downloading https://github.com/gokr/spryvm using git
  Verifying dependencies for spryvm@0.7.1
 Installing python@any version
Downloading https://github.com/nim-lang/python using git
  Verifying dependencies for python@1.2
 Installing python@1.2
   Success: python installed successfully.
 Installing ui@any version
Downloading https://github.com/nim-lang/ui using git
  Verifying dependencies for ui@0.9.2
 Installing ui@0.9.2
   Success: ui installed successfully.
 Installing nimsnappy@any version
Downloading https://github.com/dfdeshom/nimsnappy.git using git
   Warning: Package 'nimsnappy' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'nimsnappy.nim', but a file named 'tests.nim' was found. This will be an error in the future.
      Hint: If this is the primary source file in the package, rename it to 'nimsnappy.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'nimsnappy', then move it into a 'nimsnappy/' subdirectory. If it's a test file or otherwise not required to build the the package 'nimsnappy.nim', prevent its installation by adding `skipFiles = @["tests.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
  Verifying dependencies for nimsnappy@0.1.1
 Installing nimsnappy@0.1.1
   Success: nimsnappy installed successfully.
 Installing spryvm@0.7.1
   Success: spryvm installed successfully.
 Installing spry@0.7.1
   Building spry/spry using c backend
       Tip: 558 messages have been suppressed, use --verbose to show them.
     Error: nimble.nim(1106)         nimble
        ... nimble.nim(1044)         doAction
        ... nimble.nim(474)          install
        ... nimble.nim(359)          installFromDir
        ... nimble.nim(253)          buildFromDir
        ... nimble.nim(245)          buildFromDir
        ... Build failed for package: spry
        ... Details:
        ... nimble.nim(1106)         nimble
        ... nimble.nim(1044)         doAction
        ... nimble.nim(474)          install
        ... nimble.nim(359)          installFromDir
        ... nimble.nim(253)          buildFromDir
        ... nimble.nim(237)          buildFromDir
        ... tools.nim(37)            doCmd
        ... Execution failed with exit code 1
        ... Command: "/home/jpfersich/.nimble/bin/nim" c --noBabelPath -d:release --path:"/tmp/nimble_25654/githubcom_nimlangpython/src"  --path:"/tmp/nimble_25654/githubcom_nimlangui"  --path:"/tmp/nimble_25654/githubcom_dfdeshomnimsnappygit"  --path:"/tmp/nimble_25654/githubcom_gokrspryvm"  -o:"/home/jpfersich/git-stuff/spry/bin/spry" "/home/jpfersich/git-stuff/spry/src/spry.nim"
        ... Output: Hint: used config file '/home/jpfersich/.choosenim/toolchains/nim-0.19.0/config/nim.cfg' [Conf]
        ... Hint: used config file '/home/jpfersich/git-stuff/spry/src/nim.cfg' [Conf]
        ... Hint: used config file '/home/jpfersich/git-stuff/spry/src/spry.nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: spry [Processing]
        ... Hint: os [Processing]
        ... Hint: strutils [Processing]
        ... Hint: parseutils [Processing]
        ... Hint: math [Processing]
        ... Hint: bitops [Processing]
        ... Hint: algorithm [Processing]
        ... Hint: unicode [Processing]
        ... Hint: times [Processing]
        ... Hint: options [Processing]
        ... Hint: typetraits [Processing]
        ... Hint: strformat [Processing]
        ... Hint: macros [Processing]
        ... Hint: posix [Processing]
        ... Hint: ospaths [Processing]
        ... Hint: parseopt2 [Processing]
        ... spry.nim(9, 12) Warning: Use the 'parseopt' module instead; parseopt2 is deprecated [Deprecated]
        ... Hint: spryvm [Processing]
        ... Hint: sequtils [Processing]
        ... Hint: tables [Processing]
        ... Hint: hashes [Processing]
        ... ../../../../../tmp/nimble_25654/githubcom_gokrspryvm/spryvm/spryvm.nim(572, 12) Error: type mismatch: got <nil> but expected 'string'

**Comment by gokr** [comment]
I just pushed some fixes - this has to do with the new Nim v0.19.0. I threw in a "please revert to old behavior" switch.

**Comment by gokr** [comment]
I hopped onto the Pharo discord btw, if you want to chat.

**Comment by jpfersich** [comment]
I'm about to crash, it's 130 am here.

**Comment by gokr** [comment]
I think this is fixed now, at least it all works with Nim 0.20.2 and some more tweaks!
