### ISSUE TITLE
Problem in tests with variables

### ISSUE THREAD

**Issue by ray-delossantos** [gokr/spry#3]
Traceback (most recent call last)
nitest.nim(97)           nitest
nitest.nim(9)            run
ni.nim(783)              eval
ni.nim(762)              evalDo
ni.nim(743)              eval
ni.nim(634)              canEval
ni.nim(638)              canEval
ni.nim(338)              lookup
ni.nim(328)              lookup
ni.nim(334)              lookup
niparser.nim(197)        lookup
tables.nim(302)          []
tables.nim(110)          []
Error: unhandled exception: key not found: x [KeyError]
TEST FAILED

**Comment by gokr** [comment]
Not sure exactly what that was, but I pushed some more work and it works now. :)
