### ISSUE TITLE
Error from ide - SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by vonHabsi** [gokr/spry#6]
When I try to run the ide program, for the new graphical UI, I get the error "SIGSEGV: Illegal storage access. (Attempt to read from nil?)".

I am running on Debian Stretch/Sid, but Spry and libui are working okay on it.

Which version of Nim are you currently using? I am using the 0.14.2 version

**Comment by gokr** [comment]
I think I have this fixed now, I broke the code for the IDE since I made a reorg of the code. Can you build it withe makeide.sh now? And does it work? :)

**Comment by vonHabsi** [comment]
It works now. It looks like this is going to be an interesting journey.
Thanks
