### ISSUE TITLE
nimble c tests/all gives "file does not exist"

### ISSUE THREAD

**Issue by catb0t** [gokr/spry#9]
i just git pull'd and tried again:

```
cat @ oryx-kitten : ~/projects/git/spry (⎇ master??!)  $ nimble c tests/all
   Warning: File inside package 'spry' is outside of permitted namespace, should be named 'spry.nim' but was named 'ide.nim' instead. This will be an error in the future.
      Hint: Rename this file to 'spry.nim', move it into a 'spry/' subdirectory, or prevent its installation by adding `skipFiles = @["ide.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
     Error: Specified file does not exist.
```

just to make sure you know about this ;)

**Comment by gokr** [comment]
Try nimble install first. It seems nimble has changed behavior and doesnt install deps anymore if only doing nimble c blabla. Also, nimsnappy is listed as dep, and has been. :)

But I will clean up things - nimble has changed a bit. Thanks for playing!

**Comment by gokr** [comment]
I will adjust readme etc, but the travis script now does what I describe and it works.
